### ISSUE TITLE
newrelic_rpm gem is clashing with suggested way to upgrade

### ISSUE THREAD

**Issue by martingjaldbaek** [gemhome/sidekiq-delay_extensions#3]
First, thank you for taking the time to extract this gem! 🙏

I've followed the guide to upgrade, and as such included
```
Sidekiq::Extensions::DelayedClass = Sidekiq::DelayExtensions::DelayedClass
Sidekiq::Extensions::DelayedModel = Sidekiq::DelayExtensions::DelayedModel
Sidekiq::Extensions::DelayedMailer = Sidekiq::DelayExtensions::DelayedMailer
```
in my sidekiq initializer. However I'm getting a complaint when starting rails:
```
[...]/config/initializers/sidekiq.rb:5: warning: already initialized constant Sidekiq::Extensions::DelayedClass
[...]/.gem/gems/newrelic_rpm-8.5.0/lib/new_relic/agent/instrumentation/sidekiq.rb:62: warning: previous definition of DelayedClass was here
```
Is there a way to fix this on my side, or do I need to wait for https://github.com/newrelic/newrelic-ruby-agent to update [their sidekiq instrumentation](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/instrumentation/sidekiq.rb#L62) to be added to `Sidekiq::DelayExtensions::DelayedClass` instead of `Sidekiq::Extensions::DelayedClass`?

I'm guessing the suggested DelayedClass (and -Model and -Mailer) definitions above are needed when upgrading, to make sure anyone currently using them as `Sidekiq::Extensions::DelayedClass` can find them? Or to make sure there's not two different definitions of DelayedClass in use, so we override the one currently still built into sidekiq? (the readme didn't really say much about what the purpose of this was)

This is with rails 6.1.4.6, sidekiq 6.4.1 and sidekiq-delay_extensions 6.4.1

**Comment by bf4** [comment]
Hi @martingjaldbaek I apologize for just seeing this now.

The 'upgrade' portion is just so that existing jobs with the 'pre-existing' name space can be handled by the 'new' namespace.  If you're confident your upgrade is complete, you should be able to remove those lines.

Re: the warning, it's expected if you have Ruby warnings on, which I'd expect in CI or maybe dev/test, but not production. Are you seeing this in production, too?  

I expect the warning is harmless.  Have you looked at the new relic code or had further experience since writing this?

**Comment by bf4** [comment]
Closing as stale
